server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/product

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace

  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0